//! ICU4C's reading of the fifteen non-ISO calendars, 1800-2200, from
//! `icu_calendars.txt` (generated by `icu/generate.mjs`), and the days where
//! TC39's era and month-code proposal does not take ICU4C's word: the
//! published ranges of Chinese and Dangi, and the month starts ICU4C
//! misplaces inside them.
use std::collections::BTreeMap;

use crate::oracle_dates::{day_number, from_day_number};

pub type Ymd = (i64, i64, i64);

/// A run of days sharing era, year and month, as ICU4C reads them.
pub struct Row {
    pub start: i64,
    pub era: &'static str,
    pub year: i32,
    pub code: &'static str,
    pub day: u8,
    pub days_in_month: u16,
    pub months_in_year: u16,
}

/// Days ICU4C reads differently from the published calendar: first and last.
pub const MISREAD: [(&str, Ymd, Ymd); 13] = [
    ("chinese", (1917, 3, 23), (1917, 5, 20)), ("chinese", (1922, 6, 25), (1922, 8, 22)),
    ("chinese", (1954, 1, 5), (1954, 3, 4)), ("chinese", (1955, 1, 24), (1955, 3, 23)),
    ("chinese", (1987, 7, 26), (1987, 9, 22)), ("chinese", (1998, 12, 19), (1999, 2, 15)),
    ("chinese", (2012, 7, 19), (2012, 9, 15)), ("chinese", (2018, 10, 9), (2018, 12, 6)),
    ("chinese", (2027, 1, 8), (2027, 3, 7)), ("chinese", (2030, 1, 4), (2030, 3, 3)),
    ("chinese", (2057, 8, 30), (2057, 10, 27)), ("chinese", (2070, 2, 11), (2070, 4, 10)),
    ("dangi", (2017, 1, 28), (2017, 3, 27)),
];

/// Month starts in those windows as the Hong Kong Observatory publishes them
/// (hko.gov.hk T<year>e.txt), and Dangi's from the computed new moon.
pub const PUBLISHED: [(&str, (i32, u8, u8), &str); 23] = [
    ("chinese", (1917, 3, 23), "M02L"), ("chinese", (1917, 4, 21), "M03"),
    ("chinese", (1922, 6, 25), "M05L"), ("chinese", (1922, 7, 24), "M06"),
    ("chinese", (1954, 2, 3), "M01"), ("chinese", (1954, 3, 5), "M02"),
    ("chinese", (1955, 2, 22), "M02"), ("chinese", (1955, 3, 24), "M03"),
    ("chinese", (1987, 7, 26), "M06L"), ("chinese", (1987, 8, 24), "M07"),
    ("chinese", (1999, 1, 17), "M12"), ("chinese", (1999, 2, 16), "M01"),
    ("chinese", (2012, 8, 17), "M07"), ("chinese", (2012, 9, 16), "M08"),
    ("chinese", (2018, 11, 8), "M10"), ("chinese", (2018, 12, 7), "M11"),
    ("chinese", (2027, 2, 6), "M01"), ("chinese", (2027, 3, 8), "M02"),
    ("chinese", (2030, 1, 4), "M12"), ("chinese", (2030, 2, 3), "M01"),
    ("chinese", (2057, 9, 28), "M09"), ("chinese", (2070, 3, 12), "M02"),
    ("dangi", (2017, 2, 26), "M02"),
];

pub fn rows() -> BTreeMap<&'static str, Vec<Row>> {
    let mut out: BTreeMap<&str, Vec<Row>> = BTreeMap::new();
    let mut calendar = "";
    for line in include_str!("../icu_calendars.txt").lines() {
        if let Some(name) = line.strip_prefix("# ") {
            if name.contains(' ') { continue; }
            calendar = name;
            out.entry(calendar).or_default();
            continue;
        }
        let f: Vec<&str> = line.split(' ').collect();
        let (y, m, d) = (f[0][0..4].parse().unwrap(), f[0][5..7].parse().unwrap(), f[0][8..10].parse().unwrap());
        out.get_mut(calendar).unwrap().push(Row {
            start: day_number(y, m, d), era: f[1], year: f[2].parse().unwrap(), code: f[3],
            day: f[4].parse().unwrap(), days_in_month: f[5].parse().unwrap(), months_in_year: f[6].parse().unwrap(),
        });
    }
    out
}

/// Whether the proposal defines the calendar's reckoning of this day and
/// ICU4C reads it as published.
pub fn is_trusted(calendar: &str, n: i64) -> bool {
    let (year, _, _) = from_day_number(n);
    let defined = match calendar {
        "chinese" => (1900..=2100).contains(&year),
        "dangi" => (1900..=2050).contains(&year),
        _ => true,
    };
    let day = |(y, m, d): Ymd| day_number(y, m, d);
    defined && !MISREAD.iter().any(|&(c, from, to)| c == calendar && (day(from)..=day(to)).contains(&n))
}
