//! Every ISO day from 1800 to 2200 on the fifteen non-ISO calendars against
//! ICU4C, a separate implementation from the ICU4X that temporal_rs reckons
//! with: era, year, month code, day, days in the month and months in the year.
//! The reference is `icu_calendars.txt`, generated by `icu/generate.mjs`
//! through Node's ICU and committed, so the gate needs neither.
//!
//! Where TC39's era and month-code proposal (spec/proposal-intl-era-monthcode)
//! and ICU4C part ways, the proposal wins (the ranges and misread days are in `icu_reference.rs`):
//! - Japanese dates before 1873 take Gregorian eras, where ICU4C names Meiji
//!   from 1868-10-23 and the Tokugawa eras before it;
//! - Chinese dates follow the Purple Mountain Observatory only for 1900-2100
//!   and Dangi dates KASI only for 1900-2050, and are implementation-defined
//!   outside, so those days are not compared;
//! - inside those ranges ICU4C misplaces thirteen month starts, each a new moon
//!   within minutes of midnight. `MISREAD` lists them; they are held instead to
//!   the Hong Kong Observatory's published tables (Chinese) and to the new moon
//!   computed by Meeus's algorithm in Korean time (Dangi 2017, 23:57 KST).
use std::collections::BTreeMap;
use temporal_rs::{Calendar, PlainDate};
use temporal_sweeps::icu_reference::{is_trusted, rows, PUBLISHED};
use temporal_sweeps::oracle_dates::{day_number, from_day_number};

/// ICU4C's English era label as temporal_rs's era code.
fn era_code(label: &str) -> &'static str {
    match label {
        "AM" => "am", "AA" => "aa", "AH" => "ah", "Śaka" => "shaka", "AP" => "ap", "BE" => "be", "AD" => "ce",
        "Minguo" => "roc", "B.R.O.C." => "broc", "Meiji" => "meiji", "Taishō" => "taisho", "Shōwa" => "showa",
        "Heisei" => "heisei", "Reiwa" => "reiwa",
        other => panic!("no era code for ICU4C's {other}"),
    }
}

#[test]
fn should_read_every_day_as_icu4c_does() {
    let meiji_calendar_years = day_number(1873, 1, 1);
    let (mut checked, mut undefined) = (0u64, 0u64);
    let mut wrong: BTreeMap<String, (u64, Vec<String>)> = BTreeMap::new();
    for (calendar, runs) in rows() {
        let cal = Calendar::try_from_utf8(calendar.as_bytes()).unwrap();
        for (i, row) in runs.iter().enumerate() {
            let end = runs.get(i + 1).map_or(row.start + i64::from(row.days_in_month) - i64::from(row.day) + 1, |next| next.start);
            for n in row.start..end {
                if !is_trusted(calendar, n) {
                    undefined += 1;
                    continue;
                }
                let (y, m, d) = from_day_number(n);
                let date = PlainDate::try_new(y as i32, m as u8, d as u8, cal.clone()).unwrap();
                let day = i64::from(row.day) + (n - row.start);
                let mut check = |field: &str, got: String, want: String| {
                    checked += 1;
                    if got != want {
                        let entry = wrong.entry(format!("{calendar} {field}")).or_default();
                        entry.0 += 1;
                        if entry.1.len() < 3 { entry.1.push(format!("{y}-{m:02}-{d:02}: temporal_rs {got}, ICU4C {want}")); }
                    }
                };
                check("month code", date.month_code().as_str().to_string(), row.code.to_string());
                check("day", date.day().to_string(), day.to_string());
                check("days in month", date.days_in_month().to_string(), row.days_in_month.to_string());
                if row.months_in_year != 0 {
                    check("months in year", date.months_in_year().to_string(), row.months_in_year.to_string());
                }
                let (era, era_year) = match row.era {
                    "-" => (None, None),
                    _ if calendar == "japanese" && n < meiji_calendar_years => (Some("ce"), Some(y as i32)),
                    label => (Some(era_code(label)), Some(row.year)),
                };
                if era.is_none() {
                    check("year", date.year().to_string(), row.year.to_string());
                }
                check("era", format!("{:?}", date.era().map(|e| e.to_string())), format!("{:?}", era));
                check("era year", format!("{:?}", date.era_year()), format!("{era_year:?}"));
            }
        }
    }
    eprintln!("calendar fields: {checked} checked against ICU4C, {undefined} days outside the published ranges or misread by ICU4C");
    for (key, (n, examples)) in &wrong { eprintln!("  {key}: {n} differ — {}", examples.join("; ")); }
    assert!(wrong.is_empty(), "temporal_rs and ICU4C read {} field kinds differently", wrong.len());
}

#[test]
fn should_start_the_months_icu4c_misreads_where_they_are_published() {
    let mut wrong = vec![];
    for (calendar, (y, m, d), code) in PUBLISHED {
        let cal = Calendar::try_from_utf8(calendar.as_bytes()).unwrap();
        let date = PlainDate::try_new(y, m, d, cal.clone()).unwrap();
        let (py, pm, pd) = from_day_number(day_number(y.into(), m.into(), d.into()) - 1);
        let before = PlainDate::try_new(py as i32, pm as u8, pd as u8, cal).unwrap();
        if date.day() != 1 || date.month_code().as_str() != code || before.day() == 1 {
            wrong.push(format!("{calendar} {y}-{m:02}-{d:02}: {} day {}, the day before day {}", date.month_code().as_str(), date.day(), before.day()));
        }
    }
    assert!(wrong.is_empty(), "month starts disagree with the published calendar:\n{}", wrong.join("\n"));
}
